packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  puppeteer: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma

overrides:
  fast-uri: "^3.1.6"
  find-my-way: "^9.6.1"
  "@fastify/static": "^10.1.2"
  nanoid: "^3.3.18"
  cross-spawn: "^7.0.6"
  vite: "^6.4.3"
  vitest: "^3.2.6"
  express: "^4.21.2"




