-- AlterEnum
ALTER TYPE "IncidentStatus" ADD VALUE IF NOT EXISTS 'REMEDIATION_APPROVED';
ALTER TYPE "IncidentStatus" ADD VALUE IF NOT EXISTS 'REMEDIATION_EXECUTED';
ALTER TYPE "IncidentStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
